version: '3.8'

services:
  unified-medication-mcp:
    build: .
    container_name: unified-medication-mcp-server
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
      - HOST=0.0.0.0
      - OPENFDA_API_KEY=${OPENFDA_API_KEY}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs
    networks:
      - medication-network

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: unified-medication-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - unified-medication-mcp
    restart: unless-stopped
    networks:
      - medication-network
    profiles:
      - proxy

networks:
  medication-network:
    driver: bridge

volumes:
  logs:
    driver: local